### ISSUE TITLE
Suggestion: make the selection list have a search bar

### ISSUE THREAD

**Issue by UpcraftLP** [Wyn-Price/SkeletalBand#11]
Especially for larger collections it would be nice to be able to filter by jsut starting to type a sng's name in the selection box.
So like, when you click on the selection box you could make it show a cursor in the main text box and listen to keyboard input, which would then be used for filtering the list

**Comment by Wyn-Price** [comment]
Already planned, i just havnt got round to doing it

**Comment by Wyn-Price** [comment]
Closed in [f67d746](https://github.com/Wyn-Price/SkeletalBand/commit/f67d74680ac1da2c899e676cf75ac519fbbbf075)
