### ISSUE TITLE
File list enhancement

### ISSUE THREAD

**Issue by UpcraftLP** [Wyn-Price/SkeletalBand#12]
IMO it would be better to not show the file extension, unless you plan on supporting multiple file types. even then I'd rather use a small icon after the name instead.

**Comment by Wyn-Price** [comment]
Currently, you can have `.mid` or `.midi` as the midi file extension. The only real reason i can think of of showing the file extension is if somone had 2 files with the same name but diffrent extensions.  However I currently dont plan on having more extensions, and i think the 2 file same name issue isnt really that bad, so ill fix this now
