### ISSUE TITLE
Suggestion: player interaction with the band

### ISSUE THREAD

**Issue by UpcraftLP** [Wyn-Price/SkeletalBand#13]
what about making the band start/stop when you right click them?
changing the active song would IMO better be done via `Shift + Right-Click`, so you don't accidentally do it

**Comment by Wyn-Price** [comment]
maybe. I also plan to have a way to activate/deactivate the skeletons with redstone, although I do think a way to right click should be done

**Comment by Wyn-Price** [comment]
This can be closed?

**Comment by UpcraftLP** [comment]
> This can be closed?

you tell me?
and well I think yes, as 1.0.5 basically has the requeted features ^^
btw YOU can close issues, too xD
