### ISSUE TITLE
Skeletons can still play music if the other one is killed. 

### ISSUE THREAD

**Issue by darkhax** [Wyn-Price/SkeletalBand#4]
I was able to kill the skeleton that was laying down, which lead the the drumming skeleton continuing to play the song on the ground. 

![image](https://user-images.githubusercontent.com/2250798/46929698-2db0bb80-cffe-11e8-93aa-b5a4967c219c.png)

**Comment by Wyn-Price** [comment]
That dont look to good

**Comment by Wyn-Price** [comment]
Im not able to upload a new jar to curseforge, as im connected to my school wifi where twitch is blocked and therefore i cant log in
